# Generated by Django 3.2.15 on 2022-08-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_auto_20220830_0043"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentcategory",
            name="name",
        ),
        migrations.RemoveField(
            model_name="instrumentcategory",
            name="normalized_name",
        ),
    ]
