# Generated by Django 3.2.15 on 2022-08-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_auto_20220830_0052"),
    ]

    operations = [
        migrations.AddField(
            model_name="locker",
            name="lock_code",
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
