# Generated by Django 3.2.15 on 2022-08-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_locker_lock_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locker",
            name="lock_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
