# Generated by Django 3.2.15 on 2022-08-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_locker_lock_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instrument",
            old_name="book",
            new_name="book_accessory",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="case",
            new_name="case_accessory",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="cork_grease",
            new_name="cork_grease_accessory",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="ligature",
            new_name="ligature_accessory",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="mouth_piece",
            new_name="mouth_piece_accessory",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="oil",
            new_name="oil_accessory",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="reeds",
            new_name="reeds_accessory",
        ),
        migrations.RenameField(
            model_name="instrument",
            old_name="swab",
            new_name="swab_accessory",
        ),
    ]
