# Generated by Django 3.2.15 on 2022-08-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0008_rename_polishing_cloth_instrument_polishing_cloth_accessory",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrument",
            name="book_accessory",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="case_accessory",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="cork_grease_accessory",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="ligature_accessory",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="mouth_piece_accessory",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="oil_accessory",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="polishing_cloth_accessory",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="reeds_accessory",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="swab_accessory",
        ),
    ]
