# Generated by Django 3.2.15 on 2022-08-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_auto_20220830_2101"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="book_accessory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="instrument",
            name="case_accessory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="instrument",
            name="cork_grease_accessory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instrument",
            name="ligature_accessory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instrument",
            name="mouth_piece_accessory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="instrument",
            name="oil_accessory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instrument",
            name="polishing_cloth_accessory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instrument",
            name="reeds_accessory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instrument",
            name="swab_accessory",
            field=models.BooleanField(default=False),
        ),
    ]
