# Generated by Django 3.2.15 on 2022-09-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_instrument_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
