# Generated by Django 3.2.15 on 2022-09-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_instrument_instrument_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='locker',
            name='lock_code',
        ),
        migrations.AddField(
            model_name='locker',
            name='lock_assignment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.lock'),
        ),
    ]
