# Generated by Django 3.2.15 on 2022-08-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstrumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("normalized_name", models.CharField(max_length=64, unique=True)),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("woodwind instrument", "woodwind instrument"),
                            ("reed instrument", "reed instrument"),
                            ("brass instrument", "brass instrument"),
                            ("percussion instrument", "percussion instrument"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Locker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locker_number",
                    models.CharField(blank=True, max_length=3, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("broken", "broken"),
                            ("needs repair soon", "needs repair soon"),
                            ("decent condition", "decent condition"),
                            ("excellent condition", "excellent condition"),
                            ("in repair shop", "in repair shop"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("mouth_piece", models.BooleanField(default=True)),
                ("ligature", models.BooleanField(default=True)),
                ("cork_grease", models.BooleanField(default=True)),
                ("reeds", models.BooleanField(default=True)),
                ("case", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "instrument_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.instrumentcategory",
                    ),
                ),
                (
                    "locker_number",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.locker",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
