# Generated by Django 3.2.15 on 2022-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="student_name",
            new_name="student_first_name",
        ),
        migrations.AddField(
            model_name="student",
            name="student_last_name",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
