# Generated by Django 3.2.15 on 2022-08-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20220827_1725"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="home_room",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
