# Generated by Django 3.2.15 on 2022-08-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_student_home_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="home_room",
            new_name="homeroom",
        ),
    ]
