# Generated by Django 3.2.15 on 2022-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20220827_2002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(
                choices=[
                    ("fifth", "5"),
                    ("sixth", "6"),
                    ("seventh", "7"),
                    ("eighth", "8"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="homeroom",
            field=models.CharField(
                choices=[("o", "O"), ("g", "G"), ("p", "P"), ("s", "S")], max_length=10
            ),
        ),
    ]
