# Generated by Django 3.2.15 on 2022-08-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220827_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
