# Generated by Django 3.2.15 on 2022-08-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220828_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='locker_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.locker'),
        ),
    ]
