# Generated by Django 3.2.15 on 2022-08-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_instrument_locker_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='locker_number',
        ),
    ]
