# Generated by Django 3.2.15 on 2022-08-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_instrument_locker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
