# Generated by Django 3.2.15 on 2022-08-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220828_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='book',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='oil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='polishing_cloth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='swab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='cork_grease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ligature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='reeds',
            field=models.BooleanField(default=False),
        ),
    ]
