# Generated by Django 3.2.15 on 2022-08-29 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220829_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='locker_number',
        ),
        migrations.AddField(
            model_name='instrument',
            name='locker_assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.locker'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student'),
        ),
    ]
